src/inei/enssec/urls.py
from inei.enssec.models import TotalDigitacionConsulado

__author__ = 'holivares'

from django.conf.urls import patterns, url
from inei.enssec.views import (IndexView, CuestionarioView, SignOut, TotalDigitacionListView, TotalDigitacionConsuladoListView,
                               ResumenDigitacionListView, AdminView, CuestionarioDetailView, CuestionarioAjaxView)

urlpatterns = patterns('',
                       url(r'^$', IndexView.as_view(), name='index'),
                       url(r'^cuestionario/$', CuestionarioView.as_view(), name='cuestionario1'),
                       url(r'^cuestionario/(?P<pk>\d+)/$', CuestionarioDetailView.as_view(), name='cuestionario-view'),
                       url(r'^cuestionario/ajax/$', CuestionarioAjaxView.as_view(), name='cuestionario-ajax'),
                       url(r'^cuestionario/admin/$', AdminView.as_view(), name='cuestionario-admin'),
                       url(r'^cuestionario/total/$', TotalDigitacionListView.as_view(), name='cuestionario-total'),
                       url(r'^cuestionario/resumen/$', ResumenDigitacionListView.as_view(), name='cuestionario-resumen'),
                       url(r'^cuestionario/total/consulado/$', TotalDigitacionConsuladoListView.as_view(),
                           name='cuestionario-total-consulado'),
                       url(r'^logout/$', SignOut.as_view(), name='logout'),
)

src/inei/enssec/forms.py
# -*- coding: utf-8 -*-
from django.forms.extras.widgets import SelectDateWidget
from django.forms.fields import MultipleChoiceField
from django.contrib.auth.models import User

__author__ = 'holivares'
import datetime
import re

from django.forms.widgets import RadioFieldRenderer, CheckboxSelectMultiple, CheckboxFieldRenderer
from django import forms
from inei.enssec.models import Cuestionario, Consulado, Pais
from django.core.cache import cache
from django.utils.encoding import force_str
from django.utils.safestring import mark_safe
from django.utils.formats import get_format
from django.utils import six
from django.conf import settings
from django.utils import datetime_safe


RE_DATE = re.compile(r'(\d{4})-(\d\d?)-(\d\d?)$')
MONTHS = {
    1: '01', 2: '02', 3: '03', 4: '04', 5: '05', 6: '06',
    7: '07', 8: '08', 9: '09', 10: '10', 11: '11',
    12: '12', 99: '99'
}

class RadioFieldRenderer2(RadioFieldRenderer):

    def __iter__(self):
        for i, choice in enumerate(self.choices):
            if not choice[0] == '' or choice[0] is None:
                yield self.choice_input_class(self.name, self.value, self.attrs.copy(), choice, i)


class CheckboxFieldRenderer2(CheckboxFieldRenderer):

    def __iter__(self):
        for i, choice in enumerate(self.choices):
            if not choice[0] == '' or choice[0] is None:
                yield self.choice_input_class(self.name, self.value, self.attrs.copy(), choice, i)


def getConsuladoChoices():
    if cache.get('consulados'):
        choices = cache.get('consulados')
    else:
        choices = [('%s-%s-%s' % (c[0], c[1], c[2]), c[3]) for c in Consulado.objects.all().values_list('id', 'continente', 'continente__nombre', 'nombre')]
        choices.insert(0, ('', '-----------------------------'))
        cache.set('consulados', choices, 60)
    return choices


def getPaisChoices():
    if cache.get('pais'):
        choices = cache.get('pais')
    else:
        choices = [('%s-%s-%s' % (c[0], c[1], c[2]), c[3]) for c in Pais.objects.all().values_list('id', 'continente', 'continente__nombre', 'nombre')]
        choices.insert(0, ('', '-----------------------------'))
        cache.set('pais', choices, 60)
    return choices


class CSICheckboxSelectMultiple(CheckboxSelectMultiple):
    def value_from_datadict(self, data, files, name):
        # Return a string of comma separated integers since the database, and
        # field expect a string (not a list).
        return ','.join(data.getlist(name))

    def render(self, name, value, attrs=None, choices=()):
        # Convert comma separated integer string to a list, since the checkbox
        # rendering code expects a list (not a string)
        if value:
            value = value.split(',')
        return super(CSICheckboxSelectMultiple, self).render(
            name, value, attrs=attrs, choices=choices
        )


# Form field
class CSIMultipleChoiceField(MultipleChoiceField):
    widget = CSICheckboxSelectMultiple

    # Value is stored and retrieved as a string of comma separated
    # integers. We don't want to do processing to convert the value to
    # a list like the normal MultipleChoiceField does.
    def to_python(self, value):
        return value

    def validate(self, value):
        # If we have a value, then we know it is a string of comma separated
        # integers. To use the MultipleChoiceField validator, we first have
        # to convert the value to a list.
        if value:
            value = value.split(',')
        super(CSIMultipleChoiceField, self).validate(value)


class CustomSelectDateWidget(SelectDateWidget):
    def render(self, name, value, attrs=None):
        try:
            year_val, month_val, day_val = value.split('-')
        except AttributeError:
            year_val = month_val = day_val = None
            if isinstance(value, six.string_types):
                if settings.USE_L10N:
                    try:
                        input_format = get_format('DATE_INPUT_FORMATS')[0]
                        v = datetime.datetime.strptime(force_str(value), input_format)
                        year_val, month_val, day_val = v.year, v.month, v.day
                    except ValueError:
                        pass
                else:
                    match = RE_DATE.match(value)
                    if match:
                        year_val, month_val, day_val = [int(v) for v in match.groups()]
        choices = [(2000+i, i) for i in self.years]
        year_html = self.create_select(name, self.year_field, value, year_val, choices)
        choices = list(six.iteritems(MONTHS))
        month_html = self.create_select(name, self.month_field, value, month_val, choices)
        choices = [(i, "%02d" % i) for i in range(1, 32)]
        choices.append((99, '99'))
        day_html = self.create_select(name, self.day_field, value, day_val,  choices)

        output = []
        for field in forms.extras.widgets._parse_date_fmt():
            if field == 'year':
                output.append(year_html)
            elif field == 'month':
                output.append(month_html)
            elif field == 'day':
                output.append(day_html)
        return mark_safe('\n'.join(output))

    def value_from_datadict(self, data, files, name):
        y = data.get(self.year_field % name)
        m = data.get(self.month_field % name)
        d = data.get(self.day_field % name)
        return '%s-%s-%s' % (y, m, d)


class CuestionarioForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(CuestionarioForm, self).__init__(*args, **kwargs)
        self.fields['consulado_list'] = forms.ChoiceField(choices=getConsuladoChoices())
        self.fields['pais_list'] = forms.ChoiceField(choices=getPaisChoices())
        if self.instance:
            respuesta1_6 = self.instance.nu_respuesta1_6
        else:
            respuesta1_6 = self.data.get('nu_respuesta1_6')
        if self.instance:
            respuesta6 = self.instance.nu_respuesta6
        else:
            respuesta6 = self.data.get('nu_respuesta6')
        if respuesta1_6 == '1':
            self.fields['no_respuesta1_6'].required = True
            self.fields['no_respuesta1_6'].widget.attrs['readonly'] = False
        else:
            self.fields['no_respuesta1_6'].widget.attrs['readonly'] = True
        if respuesta6 == '6':
            self.fields['no_respuesta6'].required = True
            self.fields['no_respuesta1_6'].widget.attrs['readonly'] = False
        else:
            self.fields['no_respuesta6'].widget.attrs['readonly'] = True

    class Meta:
        model = Cuestionario
        widgets = {
            'nu_respuesta1_1': forms.TextInput(attrs={'class': 'span1 numero bit'}),
            'nu_respuesta1_2': forms.TextInput(attrs={'class': 'span1 numero bit'}),
            'nu_respuesta1_3': forms.TextInput(attrs={'class': 'span1 numero bit'}),
            'nu_respuesta1_4': forms.TextInput(attrs={'class': 'span1 numero bit'}),
            'nu_respuesta1_5': forms.TextInput(attrs={'class': 'span1 numero bit'}),
            'nu_respuesta1_6': forms.TextInput(attrs={'class': 'span1 numero bit'}),
            'no_respuesta1_6': forms.TextInput(attrs={'class': 'span12 texto'}),
            'nu_respuesta2': forms.TextInput(attrs={'class': 'span1 numero'}),
            'nu_respuesta3': forms.TextInput(attrs={'class': 'span1 numero'}),
            'nu_respuesta4': forms.TextInput(attrs={'class': 'span1 numero'}),
            'nu_respuesta5': forms.TextInput(attrs={'class': 'span1 numero'}),
            'nu_respuesta6': forms.TextInput(attrs={'class': 'span1 numero'}),
            'no_respuesta6': forms.TextInput(attrs={'class': 'span12 texto'}),
            'tomo': forms.TextInput(attrs={'class': 'span3   numero', 'readonly': 'readonly'}),
            'fecha': CustomSelectDateWidget(years=(13, 14, 99)),
            'edad': forms.TextInput(attrs={'class': 'span12 numero', 'maxlength': 2}),
            'dni': forms.TextInput(attrs={'class': 'span12 numero'}),
            'sexo': forms.Select(attrs={'class': 'span12'}),
            'encuestado': forms.TextInput(attrs={'class': 'span12 texto'}),
            'observacion': forms.Textarea(attrs={'class': 'span12 texto', 'rows': 2}),
            'ciudadResidencia': forms.TextInput(attrs={'class': 'span12 texto'}),
            'ficha': forms.TextInput(attrs={'class': 'span3 numero'})
        }
        exclude = ('usuario', 'continentePais', 'continenteConsulado', 'consulado', 'pais', )


class TotalDigitacionForm(forms.Form):
    date_range = forms.CharField(max_length=70, required=False, widget=forms.TextInput(attrs={'class': 'date_picker span10'}))


class ResumenDigitacionForm(TotalDigitacionForm):
    digitador = forms.ModelChoiceField(queryset=User.objects.filter(is_staff=False, is_superuser=False, is_active=True),
                                       empty_label='---Seleccione---', widget=forms.Select(attrs={'class': 'span7'}))

src/inei/enssec/templates/cuestionario/admin.html
{% extends 'base.html' %}
{% load static from staticfiles %}
{% load url from future %}
{% block css %}
    <style>
        #tbl_data thead tr th{
            text-align: center;
        }
        #tbl_data tbody tr td{
            text-align: center;
        }

    </style>
{% endblock %}
{% block contenido %}
    <div style="position: absolute; right: 20px; top:90px;">
        <a href="{% url 'logout' %}"><h4>Cerrar sesion</h4></a>
    </div>
    <!-- bootstrap css -->
    <div class="container-fluid">
        <div class="dashboard-wrapper">
            <div class="left-sidebar">
                <div class="row-fluid">
                    <div class="span8 offset2">
                        <div class="widget">
                            <div class="widget-header">
                                <div class="title">Administración</div>
                            </div>
                            <div class="widget-body">
                                <form class="form-horizontal no-margin" id="id_form" name="form">
                                    {% csrf_token %}
                                    <div class="tab-content" id="myTabContent">
                                        <div id="step1" class="tab-pane fade active in">
                                            <div class="row-fluid">
                                                <div class="span12">
                                                    <a href="{% url 'cuestionario-total-consulado' %}">Reporte total de digitación por consulado</a><br/>
                                                    <a href="{% url 'cuestionario-total' %}">Reporte total de digitación</a> <br/>
                                                    <a href="{% url 'cuestionario-resumen' %}">Reporte resumen de digitación</a> <br/>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block js %}
{% endblock %}

src/inei/enssec/templates/cuestionario/resumen-digitacion.html
{% extends 'base.html' %}
{% load static from staticfiles %}
{% load querytags %}
{% load url from future %}
{% block css %}
    <style>
        #tbl_data thead tr th{
            text-align: center;
        }
        #tbl_data tbody tr td{
            text-align: center;
        }
    </style>
{% endblock %}
{% block contenido %}
    <div style="position: absolute; right: 20px; top:90px;">
        <a href="{% url 'logout' %}"><h4>Cerrar sesion</h4></a>
    </div>
    <!-- bootstrap css -->
    <div class="container-fluid">
        <div class="dashboard-wrapper">
            <div class="left-sidebar">
                <div class="row-fluid">
                    <div class="span8 offset2">
                        <div class="widget">
                            <div class="widget-header">
                                <div class="title">Reporte Resumen de digitación</div>
                            </div>
                            <div class="widget-body">
                                <form class="form-horizontal no-margin" id="id_form" name="form">
                                    <div class="tab-content" id="myTabContent">
                                        <div id="step1" class="tab-pane fade active in">
                                            <div class="row-fluid">
                                                <div class="span12">
                                                    <div class="widget">
                                                        <div class="widget-header">
                                                            <div class="title">Opciones de busqueda</div>
                                                            <span class="tools">
                                                                <a data-original-title="" class="fs1" aria-hidden="true" data-icon="" href="{% url 'cuestionario-admin' %}" title="Volver"> </a>
                                                            </span>
                                                        </div>
                                                        <div class="widget-body">
                                                            <div class="row-fluid">
                                                                <div class="span7">
                                                                    <div class="control-group">
                                                                        <label class="control-label" for="id_date_range">
                                                                            Periodo de Consulta
                                                                        </label>
                                                                        <div class="controls">
                                                                            <div class="input-append">
                                                                                {{ form.date_range }}
                                                                                    <span class="add-on">
                                                                                      <i class="icon-calendar">
                                                                                      </i>
                                                                                    </span>
                                                                            </div>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                                <div class="span5">
                                                                    <div class="control-group">
                                                                        <label style="float: left;padding-top: 5px;text-align: right;width: 60px;" for="id_digitador">
                                                                            Digitador
                                                                        </label>
                                                                        <div class="controls" style="margin-left: 70px;">
                                                                            {{ form.digitador }}
                                                                            <button class="btn btn-success bottom-margin" type="submit">Buscar</button>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="row-fluid">
                                                <div class="span12">
                                                    <table class="table table-bordered table-condensed table-hover" id="tbl_data">
                                                        <thead>
                                                            <tr>
                                                                <th>Fecha</th>
                                                                <th>Digitador</th>
                                                                <th>Consulado</th>
                                                                <th>Numero Tomo</th>
                                                                <th>Numero Ficha</th>
                                                                <th>Opciones</th>
                                                            </tr>
                                                        </thead>
                                                        <tbody>
                                                            {% for item in object_list %}
                                                            <tr>
                                                                <td>{{ item.fecha }}</td>
                                                                <td>{{ item.usuario }}</td>
                                                                <td>{{ item.consulado }}</td>
                                                                <td>{{ item.tomo}}</td>
                                                                <td>{{ item.ficha }}</td>
                                                                <td><a href="{% url 'cuestionario-view' item.id %}"><i class="icon-edit"></i></a></td>
                                                            </tr>
                                                            {% endfor %}
                                                        </tbody>
                                                    </table>
                                                    <div class="pagination pagination-right">
                                                        <div style="float: left">
                                                            Mostrando {{ page_obj|length }} registros de {{ paginator.count }}
                                                        </div>
                                                      <ul>
                                                        <li><a href="{% querystring "page"=1 %}" title="Primero">&lt;&lt;</a></li>
                                                        {% if page_obj.has_previous %}
                                                        <li><a href="{% querystring "page"=page_obj.previous_page_number %}" title="Anterior">&lt;</a></li>
                                                        {% endif %}
                                                        <li class="active"><a href="#">{{ page_obj.number }}</a></li>
                                                        {% if page_obj.has_next %}
                                                        <li><a href="{% querystring "page"=page_obj.next_page_number %}" title="Siguiente">&gt;</a></li>
                                                        {% endif %}
                                                        <li><a href="{% querystring "page"=paginator.num_pages %}" title="Ultimo">&gt;&gt;</a></li>
                                                      </ul>
                                                    </div>
                                                <a href="{% url 'cuestionario-admin' %}" class="btn btn-primary" style="float: right">Volver</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block js %}
    <script type="text/javascript" src="{% static 'theme/js/date-picker/date.js' %}"></script>
    <script type="text/javascript" src="{% static 'theme/js/date-picker/daterangepicker.js' %}"></script>

    <script type="text/javascript">
      $('.date_picker').daterangepicker({
        opens: 'right',
        format: 'yyyy-MM-dd',
        separator: ' | ',
        locale: {
            applyLabel: 'Aplicar',
            clearLabel:"Limpiar",
            fromLabel: 'Desde',
            toLabel: 'Hasta',
            weekLabel: 'W',
            customRangeLabel: 'Periodo',
            daysOfWeek: ["Dom", "Lun", "Mar", "Mié", "Jue", "Vie", "Sáb"],
            monthNames: ["Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"],
            firstDay: 0
        }
      });
    </script>
{% endblock %}

src/inei/enssec/templates/cuestionario/total-digitacion-consulado.html
{% extends 'base.html' %}
{% load static from staticfiles %}
{% load querytags %}
{% load url from future %}
{% block css %}
    <style>
        #tbl_data thead tr th {
            text-align: center;
        }

        #tbl_data tbody tr td {
            text-align: center;
        }

    </style>
{% endblock %}
{% block contenido %}
    <div style="position: absolute; right: 20px; top:90px;">
        <a href="{% url 'logout' %}"><h4>Cerrar sesion</h4></a>
    </div>
    <!-- bootstrap css -->
    <div class="container-fluid">
        <div class="dashboard-wrapper">
            <div class="left-sidebar">
                <div class="row-fluid">
                    <div class="span8 offset2">
                        <div class="widget">
                            <div class="widget-header">
                                <div class="title">Reporte total de digitación por Consulado</div>
                            </div>
                            <div class="widget-body">
                                <form class="form-horizontal no-margin" id="id_form" name="form">
                                    <div class="tab-content" id="myTabContent">
                                        <div id="step1" class="tab-pane fade active in">
                                            <div class="row-fluid">
                                                <div class="span12">
                                                    <div class="widget">
                                                        <div class="widget-header">
                                                            <div class="title">Resultado de la busqueda</div>
                                                        </div>
                                                        <div class="widget-body">
                                                            <table class="table table-bordered table-condensed table-hover"
                                                                   id="tbl_data">
                                                                <thead>
                                                                <tr>
                                                                    <th>Consulado</th>
                                                                    <th>N° Tomo</th>
                                                                    <th>N° Meta</th>
                                                                    <th>N° Encuestas</th>
                                                                    <th>N° Recepcionado</th>
                                                                    <th>N° Duplicados o Restantes</th>
                                                                    <th>Total Digitado</th>
                                                                </tr>
                                                                </thead>
                                                                <tbody>
                                                                {% for item in object_list %}
                                                                    <tr>
                                                                        <td>{{ item.consulado }}</td>
                                                                        <td>{{ item.tomo }}</td>
                                                                        <td>{{ item.meta }}</td>
                                                                        <td>{{ item.encuestas }}</td>
                                                                        <td>{{ item.recepcionado }}</td>
                                                                        <td>{{ item.repetidos }}</td>
                                                                        <td>{{ item.fichas }}</td>
                                                                    </tr>
                                                                {% endfor %}
                                                                </tbody>
                                                            </table>
                                                            <div class="pagination pagination-right">
                                                                <div style="float: left">
                                                                    Mostrando {{ page_obj|length }} registros de {{ paginator.count }}
                                                                </div>
                                                              <ul>
                                                                <li><a href="{% querystring "page"=1 %}" title="Primero">&lt;&lt;</a></li>
                                                                {% if page_obj.has_previous %}
                                                                <li><a href="{% querystring "page"=page_obj.previous_page_number %}" title="Anterior">&lt;</a></li>
                                                                {% endif %}
                                                                <li class="active"><a href="#">{{ page_obj.number }}</a></li>
                                                                {% if page_obj.has_next %}
                                                                <li><a href="{% querystring "page"=page_obj.next_page_number %}" title="Siguiente">&gt;</a></li>
                                                                {% endif %}
                                                                <li><a href="{% querystring "page"=paginator.num_pages %}" title="Ultimo">&gt;&gt;</a></li>
                                                              </ul>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <a href="{% url 'cuestionario-admin' %}" class="btn btn-primary" style="float: right">Volver</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block js %}
    <script type="text/javascript" src="{% static 'theme/js/date-picker/date.js' %}"></script>
    <script type="text/javascript" src="{% static 'theme/js/date-picker/daterangepicker.js' %}"></script>

    <script type="text/javascript">
      $('.date_picker').daterangepicker({
        opens: 'right',
        format: 'yyyy-MM-dd',
        separator: ' | ',
        locale: {
            applyLabel: 'Aplicar',
            clearLabel:"Limpiar",
            fromLabel: 'Desde',
            toLabel: 'Hasta',
            weekLabel: 'W',
            customRangeLabel: 'Periodo',
            daysOfWeek: ["Dom", "Lun", "Mar", "Mié", "Jue", "Vie", "Sáb"],
            monthNames: ["Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"],
            firstDay: 0
        }
      });
    </script>
{% endblock %}